[project]
name = "model-split-verification"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "torch==1.13.1+cpu",
    "numpy==1.24.0",
    "onnxruntime==1.13.1"
]

[tool.pip]
extra-index-url = ["https://download.pytorch.org/whl/cpu"]